In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("stud.csv")

In [4]:
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,NaN
1,female,group C,some college,standard,completed,69,90,88.0
2,female,group B,master's degree,standard,none,90,95,93.0
3,male,group A,associate's degree,free/reduced,none,47,57,44.0
4,male,group C,some college,standard,none,76,78,75.0
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95.0
996,male,group C,high school,free/reduced,none,62,55,55.0
997,female,group C,high school,free/reduced,completed,59,71,65.0
998,female,group D,some college,standard,completed,68,78,77.0
999,female,group D,some college,free/reduced,none,77,86,86.0

In [5]:
df["math score"].mean()

np.float64(66.089)

In [6]:
df["math score"].median()

66.0

In [18]:
df["math score"].mode()

0    65
Name: math score, dtype: int64

In [22]:
data = {
    "stud":["abhi","sachin" , "shang" , "mon2","wizard"],
    "math" : [85,75,78,75,85]
}

In [23]:
df2= pd.DataFrame(data)

In [24]:
df2

     stud  math
0    abhi    85
1  sachin    75
2   shang    78
3    mon2    75
4  wizard    85

In [28]:
df2["math"].mode()

0    75
1    85
Name: math, dtype: int64

In [13]:
df2["math"].median()

85.0

In [14]:
df2["math"].mean()

np.float64(84.4)

In [15]:
df2.describe()

            math
count   5.000000
mean   84.400000
std     8.619745
min    76.000000
25%    78.000000
50%    85.000000
75%    85.000000
max    98.000000

In [16]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   stud    5 non-null      object
 1   math    5 non-null      int64
dtypes: int64(1), object(1)
memory usage: 212.0+ bytes